a=[]
a1=int(input("entre marks of first student"))
a.append(a1)
a2=int(input("entre marks of first student"))
a.append(a2)
a3=int(input("entre marks of first student"))
a.append(a3)
a4=int(input("entre marks of first student"))
a.append(a4)
a5=int(input("entre marks of first student"))
a.append(a5)
a6=int(input("entre marks of first student"))
a.append(a6)
a7=int(input("entre marks of first student"))
a.append(a7)
a.sort()
print(a)